export const Data = [
  {
    image: require('../assets/images/65726a0b-cde2-4c25-a1e4-b2df85142283-removebg-preview.png'),
    name: 'Shrimp fried rice',
    detail: 'Fried rice with shirmps \nand spicy souce',
    currency: '$',
    price: '5.30',
    id: 1,
  },
  {
    image: require('../assets/images/roast-chicken.png'),
    name: 'Roast Chicken',
    detail: 'Tender, golden-brown perfection.',
    currency: '$',
    price: '7.30',
    id: 2,
  },
  {
    image: require('../assets/images/moussaka.png'),
    name: 'Moussaka',
    detail: 'Layered eggplant, meat, and with creamy sauce.',
    currency: '$',
    price: '8',
    id: 3,
  },
  {
    image: require('../assets/images/tandori-chicken.png'),
    name: 'Tandori Chicken',
    detail: 'Spicy, smoky delight.',
    currency: '$',
    price: '9.40',
    id: 4,
  },
  // {
  //   image: require('../assets/images/lasagne.png'),
  //   name: 'Lasagne',
  //   detail: 'Cheesy pasta layers, \npure comfort.',
  //   currency: '$',
  //   price: '9.80',
  //   id: 5,
  // },
  {
    image: require('../assets/images/biryani.png'),
    name: 'Biryani',
    detail: 'Fragrant rice, flavorful spices, pure delight.',
    currency: '$',
    price: '10',
    id: 6,
  },
  {
    image: require('../assets/images/goulash.png'),
    name: 'Goulash',
    detail: 'Hearty, rich, \nHungarian comfort.',
    currency: '$',
    price: '10.3',
    id: 7,
  },
];
